In [1]:
import pandas as pd

In [3]:
archivo = r"/content/drive/MyDrive/Colab Notebooks/Data/Dataframe2.csv"

data2 = pd.read_csv(archivo, sep=";")

print(data2)

   id  weight  height  age
0   1   143.5     5.3   28
1   2   154.2     5.5   45
2   3   342.3     5.1   99
3   4   144.5     5.5   33
4   5   133.2     5.4   54
5   6   124.1     5.1   21
6   7   129.2     5.3   42

In [4]:
r_data2 = data2.rename(columns={
    "id":"id",
    "weight":"PESO",
    "height":"ALTURA",
    "age":"EDAD"
    })

print(r_data2)

   id   PESO  ALTURA  EDAD
0   1  143.5     5.3    28
1   2  154.2     5.5    45
2   3  342.3     5.1    99
3   4  144.5     5.5    33
4   5  133.2     5.4    54
5   6  124.1     5.1    21
6   7  129.2     5.3    42

In [7]:
converpeso = 0.453592
converaltura = 0.3048

cpdata2 = r_data2["PESO"] * converpeso
cadata2 = r_data2["ALTURA"] * converaltura

newdata2 = pd.DataFrame({
    "id":r_data2["id"],
    "PESO":cpdata2,
    "ALTURA":cadata2,
    "EDAD": r_data2["EDAD"]
})

print(newdata2)

   id        PESO   ALTURA  EDAD
0   1   65.090452  1.61544    28
1   2   69.943886  1.67640    45
2   3  155.264542  1.55448    99
3   4   65.544044  1.67640    33
4   5   60.418454  1.64592    54
5   6   56.290767  1.55448    21
6   7   58.604086  1.61544    42